### ISSUE TITLE
Printing the Case

### ISSUE THREAD

**Issue by Mikescops** [steindevices/ESP32-LyraT-DSP#1]
Hello,

Thanks a lot for your work, I happened to play around the LyraT a year ago and I created a setup similar to yours with the exact same screen. 

I am actually using the logitech media server and the squeezebox-esp32. Which allows me to control the esp32 and the DAC from a remote media player and also play it in sync with other devices.

The last thing i was missing is the case, i'm bad at doing 3D models so i'm glad i stumbled upon your work.

I will try to print it in the upcoming weeks and share the result here!

Cheers!

**Comment by steindevices** [comment]
Hi,

The case .STL file that's currently posted is for the DSP without the display. I'll post my other .STL for the case with support for a display.

Hope it works out for you.

**Comment by Mikescops** [comment]
Awesome, thanks, let me know when it's pushed 😄

**Comment by steindevices** [comment]
I have pushed two .STL files (lid and base) for the OLED version of the case. I'm out of town right now and don't recall which screw sizes/lengths work best, but I believe they were 3mm allen key heads. You will need four to attach the lid to the base and four to attach the OLED display to the lid. YMMV

**Comment by steindevices** [comment]
Closing
