### ISSUE TITLE
i2c error loading audio codec

### ISSUE THREAD

**Issue by awholecorndog** [steindevices/ESP32-LyraT-DSP#2]
After uploading to board it has hangs loading the audio codec. Using arduino 1.8.19 with all libraries and boards updated to latest version.
Serial output;

I-DSP: Initializing audio codec via I2C...
E (1740) i2c: i2c_param_config(684): i2c clock choice is invalid, please check flag and frequency
E (2742) i2c: i2c_set_pin(882): scl and sda gpio numbers are the same
E (3743) i2c: i2c_set_pin(882): scl and sda gpio numbers are the same
*several more "scl and sda gpio numbers are the same"*
E-DSP: Audio codec initialization failed!

**Comment by steindevices** [comment]
Issue appears to be due to changes in the ESP32 Arduino board library from v1.x to 2.x. Modified dsp_process.cpp to conform to new clock frequency setting mechanism. Please update and re-test.

**Comment by awholecorndog** [comment]
Uploaded and seems to be working fine. The wifi uploading is nice and I like the ability to see how it is configured using the telnet connection. I will try out some different settings over the next few days. Thanks.
