### ISSUE TITLE
Pop/thump when signal starts or stops

### ISSUE THREAD

**Issue by awholecorndog** [steindevices/ESP32-LyraT-DSP#3]
Hello, I am getting a pretty loud spike when the DSP starts or stops. Below is a screenshot of the output recorded with audacity. First spike is when the input is started and the second is a bit more than 6 seconds after it stopped. It does this every time it receives or loses a signal. I tested with no gain, delay or filters, and even with the DSP disabled. 

![Screenshot from 2023-09-20 08-35-07](https://github.com/steindevices/ESP32-LyraT-DSP/assets/29509752/f5483cc5-6e4f-412a-a282-421b235de6b4)

**Comment by steindevices** [comment]
Can you clarify "start" and "stop"? Is this when you send commands to the DSP via the serial connection and/or Telnet? Is it when you connect and disconnect an audio cable? Or is it when the actual analog signal to the board starts and stops? Also, are you using one of the example configs from my GitHub project or your own filters? Let me know.

**Comment by awholecorndog** [comment]
When I play a file or pause/stop it, or a song ends and the next starts it will spike. It does this with any configuration. Any one of the examples or a custom one I set up with no gain, delay or filters. I also tried disabling the DSP using telnet with the d command. On the screenshot the first spike is when I played the file and the second is a little more than 6 seconds after I paused it. The level of the signal does not seem to make any difference. In the screenshot the file is barely audible as I kept lowering the volume out from a separate PC to see if it changed. I have tried several sources to try and isolate the spike with the same issue on all of them (receiver pre-out from HDMI source, PC line out, phone). Different power sources. It will also spike when the board it either powered on (from on board switch or plugging in) or reset. If I physically remove the DSP board and jumper the 2 3.5mm plugs together the spike is gone.

I will mess with it some more tonight to see if I can isolate the problem any more. Any recommendations appreciated.

**Comment by awholecorndog** [comment]
It is a lot like a thump from a amp powering on that does not have a built in delay.

**Comment by steindevices** [comment]
Hmmm... This ESP32 board is actually pretty sophisticated and includes the ability to sense an active signal as well as perform automatic gain control. I am wondering if it is associated with one of these settings and that your sources are quieter than mine which is exposing the issue.  If so, I may be able to defeat it. 

I'll try to reproduce the issue on my end and get back to you.

**Comment by awholecorndog** [comment]
One other thing I noticed is that when the spike happens the green led behind the WROVER module blinks. Both when a signal is acquired and when lost. It does not blink on power on.
![ESP32-LyraT (WROVER-E)_1-2](https://github.com/steindevices/ESP32-LyraT-DSP/assets/29509752/c3ce3964-764b-4f8a-95d4-36dad8f4c0f6)

Also the power on spike is much less then the signal acquire/loss spike, and not really a big deal. 

Is there a way I could load the original sketch via a older board manager or something.

**Comment by awholecorndog** [comment]
One other thing I noticed is that the green led behind the WROVER module blinks when the spike occurs. It does not blink on power up. The spike on power up is much less and not really a problem.
![ESP32-LyraT (WROVER-E)_1-2](https://github.com/steindevices/ESP32-LyraT-DSP/assets/29509752/a9c0b8bc-fc98-4876-8eaf-9ec9a4c3e6dd)

Is there a older board manager or something that will work with the original sketch?

**Comment by steindevices** [comment]
Ah! That's good information as the green LED means that the audio is likely clipping at either the input or the output stage. You can check this by monitoring the clipping count. The clipping count is displayed for each channel when you type the 'i' command at the Serial or Telnet interface. Check the counts before the thump, then check it again after. See whether the input or output clipping goes up.

**Comment by steindevices** [comment]
FYI... the sound you are hearing on power up/reset is on my end as well and is something I have been trying to minimize. This may be inherent to the way the ES8388 chip initializes prior to the Arduino environment starting up. So that's somewhat of a known issue. However, this other problem is very strange. So just to make sure - you are saying this happens when there is no signal between songs? In other words, you play two tracks back-to-back and you hear this "pop" during the silence between tracks?

**Comment by awholecorndog** [comment]
I have not tried back to back with a playlist. Just one song at a time manually with several seconds in between as I crossed the room to select another. That was when I first noticed it after one track ended. I originally suspected the pop was due to the headphone jack on my phone, but then it was doing it when I was not handling the phone. I will try a playlist in a bit, you are probably right that it won't do it. It takes 5 or 6 seconds after play stops. Then I will compare the before and after clipping information as well. 
The power up spike is easily remedied with a speaker delay relay. Or just leave it on.

**Comment by awholecorndog** [comment]
Back to back play is fine. Only pops at the beginning and end. Tried several different cables and sources. Every source starts with 0 clipping counts. Once play starts input and output clipping numbers jump (primarily on input 0), but only when an output is connected. If I leave the output disconnected all clipping stays at 0. I will post a few telnet samples below;
PC before play;
I-DSP: Channel A: Left
I-DSP:   Input 0 = 1
I-DSP:   Input 1 = 0
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 0
I-DSP:   Output clipping count = 0
I-DSP:   Filter count = 0

I-DSP: Channel B: Right
I-DSP:   Input 0 = 0
I-DSP:   Input 1 = 1
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 0
I-DSP:   Output clipping count = 0
I-DSP:   Filter count = 0

After starting play;
I-DSP: Channel A: Left
I-DSP:   Input 0 = 1
I-DSP:   Input 1 = 0
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 935
I-DSP:   Output clipping count = 935
I-DSP:   Filter count = 0

I-DSP: Channel B: Right
I-DSP:   Input 0 = 0
I-DSP:   Input 1 = 1
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 0
I-DSP:   Output clipping count = 0
I-DSP:   Filter count = 0

After play finishes;
I-DSP: Channel A: Left
I-DSP:   Input 0 = 1
I-DSP:   Input 1 = 0
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 1669
I-DSP:   Output clipping count = 935
I-DSP:   Filter count = 0

I-DSP: Channel B: Right
I-DSP:   Input 0 = 0
I-DSP:   Input 1 = 1
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 0
I-DSP:   Output clipping count = 0
I-DSP:   Filter count = 0

Phone after play, different cable;

I-DSP: Channel A: Left
I-DSP:   Input 0 = 1
I-DSP:   Input 1 = 0
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 4169
I-DSP:   Output clipping count = 2507
I-DSP:   Filter count = 0

I-DSP: Channel B: Right
I-DSP:   Input 0 = 0
I-DSP:   Input 1 = 1
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 100 millis
I-DSP:   Delay samples = 4410
I-DSP:   Input clipping count = 8
I-DSP:   Output clipping count = 0
I-DSP:   Filter count = 0


I wonder if there is a problem with my board.

**Comment by steindevices** [comment]
Definitely clipping. Might have something to do with the delay setting though odd that it shows clipping at input. Looking at it now.

**Comment by steindevices** [comment]
Can you check to see if you get clipping when using the 's' (stop)  and 'r' (run) commands alternating back and forth? Also, same for 'e' (enable) and 'd' (disable). Very, very odd.

**Comment by steindevices** [comment]
I tested with your delay settings and no clipping on my end.  If you lower the output level from your sources, does that reduce the clipping numbers?

**Comment by awholecorndog** [comment]
I will try that in the morning. 
Thanks for your help. This is a great project.

**Comment by steindevices** [comment]
I've upgraded to the most recent ESP32 board library (2.0.13) and not seeing this issue, so I am stumped. As I mentioned, you will definitely get noise during resets and shutdowns, as well as when you connect and disconnect an audio cable from the board. You will also get clipping when playing a source that is too loud at the input or amplified too much in the DSP, but I've never had clipping when the input is silent from either of my two boards. 

Just to be clear, are you connecting and disconnecting cables from either the board or the audio source when you hear the thump? That would definitely cause clipping.

**Comment by steindevices** [comment]
One more thing. Are you saying the clipping counts don't go up if the output is disconnected but they do if the output is connected?

**Comment by awholecorndog** [comment]
I did several tests to try and narrow the variables. The board was restarted between all connection changes. It only pops when a signal is acquired or lost at the left input. The DSP can be started and stopped while it has a signal with no issues. The clipping numbers only change when it pops, and the led only lights when it pops. The right input does not do this.

Input signal is output from a PC at 35% volume. No output cable attached to board. Board input connected to left only. I get a pop at signal start and another 6 seconds after signal loss.

I think that there is a problem with the left input on the board.

I can work with this though as I plan on using this for a BOSS subwoofer setup and I will only have one input channel. Using the right input I can use the DSP to split that signal to both outputs with each output signal having its own DSP settings.

Loaded this configuration to the board and no more pops!
I-DSP:   Sampling rate = 44100
I-DSP:   Sampling bits = 16
I-DSP:   Sampling delay = 4.353742 ms
I-DSP:   Dither = ON

I-DSP: Channel A: BOSS1
I-DSP:   Input 0 = 0
I-DSP:   Input 1 = 1
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 0 millis
I-DSP:   Delay samples = 0
I-DSP:   Input clipping count = 0
I-DSP:   Output clipping count = 0
I-DSP:   Filter count = 2
I-DSP:   Filter 1 coeffs = 7.21943416266700e-05 1.44388683253340e-04 7.21943416266700e-05 -1.97558262910536e+00 9.75871406471866e-01 (FLT)
I-DSP:     Low Pass: Frequency=  120.0  Q=7.00000000000000e-01  Gain= 0.0
I-DSP:   Filter 2 coeffs = 7.21943416266700e-05 1.44388683253340e-04 7.21943416266700e-05 -1.97558262910536e+00 9.75871406471866e-01 (FLT)
I-DSP:     Low Pass: Frequency=  120.0  Q=7.00000000000000e-01  Gain= 0.0

I-DSP: Channel B: BOSS2
I-DSP:   Input 0 = 0
I-DSP:   Input 1 = 1
I-DSP:   Gain = 0.000000 dB
I-DSP:   Scaling factor = 1.000000
I-DSP:   User delay = 0 millis
I-DSP:   Delay samples = 0
I-DSP:   Input clipping count = 0
I-DSP:   Output clipping count = 0
I-DSP:   Filter count = 2
I-DSP:   Filter 1 coeffs = 7.21943416266700e-05 1.44388683253340e-04 7.21943416266700e-05 -1.97558262910536e+00 9.75871406471866e-01 (FLT)
I-DSP:     Low Pass: Frequency=  120.0  Q=7.00000000000000e-01  Gain= 0.0
I-DSP:   Filter 2 coeffs = 7.21943416266700e-05 1.44388683253340e-04 7.21943416266700e-05 -1.97558262910536e+00 9.75871406471866e-01 (FLT)
I-DSP:     Low Pass: Frequency=  120.0  Q=7.00000000000000e-01  Gain= 0.0

Now to do a bit more testing, but I think the problem is solved. Thanks for helping me work through this problem, and thanks for designing this firmware. This project really has a lot of potential.

One more question. I plan on using this mainly for movies and such. Should the sampling rate be changed to 48000? If so how is that done.

**Comment by steindevices** [comment]
That's really unfortunate about the left channel issue. There is a possibility that there is a setting I am not initializing properly for the onboard ES8388 chip, but without being able to duplicate the issue I don't have any way to solve it. :( If you decide to try this on another ESP32-LyraT board, let me know if you run into the same issue.

Regarding setting the sampling rate to 48000, just change the value in dsp_process.h as follows and rebuild:

#define DSP_SAMPLE_RATE         48000             // The sample rate

That said, with a low pass filter at 120Hz you won't really benefit. In fact, you could probably set it to 16000 and it would sound the same since you won't have any frequencies above 8000Khz (1/2 the Nyquist rate) to filter.

**Comment by awholecorndog** [comment]
It is strange. Even if the left channel is bypassed in the configuration it will pop if a signal is received or lost on it. It needs to be completely disconnected in the wiring. The 6 second delayed pop after signal loss really seems like something turning off.

Either way I figured out a way to work around the issue and the board is working nicely. I am using it with a little 50w wondom board amp that has a startup and shutdown pop, so I already have a relay board to delay the speaker connection. Therefore the small power up pop from the DSP is not an issue.

Someone on AVS forum said they ordered the lyrat board. If they have the same issue then it may be the firmware, but I would think you would have it as well. The pop is unmissable. Most likely the board I got has something buggy.

**Comment by awholecorndog** [comment]
One other question. In the examples any filters are listed twice for each one. 

  {0, DSP_FILTER_HIGH_PASS, 120, 0.7, 0.0 },
  {0, DSP_FILTER_HIGH_PASS, 120, 0.7, 0.0 },
  {1, DSP_FILTER_HIGH_PASS, 120, 0.7, 0.0 },
  {1, DSP_FILTER_HIGH_PASS, 120, 0.7, 0.0 },

Not a problem really. Just curious if it is necessary.

**Comment by steindevices** [comment]
Excellent question!

The reason they are listed twice is that this provides a steeper roll-off cut than using a single filter. Specifically, a single high pass filter provides a 6dB/octave roll-off while two increases it to 12dB/octave. This is called cascading filters to achieve higher orders. You can see this change if you plot the transfer curve (frequency plot) by using the 'p' command in the DSP. When you compare the two plots you'll see the difference.
