### ISSUE TITLE
Incorporating Bluetooth a2dp running into issues with i2s

### ISSUE THREAD

**Issue by hhemmati81** [steindevices/ESP32-LyraT-DSP#5]
I am trying to use the Bluetooth library by Phil Schatzmann linked below as an audio source.
https://github.com/pschatzmann/ESP32-A2DP

I created a new setup function that runs after the DSP setup in the main task. I am running into i2s driver install failed. I assume that's because the DSP has already installed the i2s driver.  I tried changing the port number but that caused core panic.

**Comment by steindevices** [comment]
You are correct that the I2S bus is already in use. The issue you are running into is that the I2S bus is used by the ESP32 to communicate to the ES8388 ADC board. The documentation showing the usage is available from EspressIf here:

https://espressif-docs.readthedocs-hosted.com/projects/esp-adf/en/latest/design-guide/dev-boards/board-esp32-lyrat-v4.3.html

**Comment by hhemmati81** [comment]
Yeah, I just have to figure out how to write the raw audio data to the existing i2s bus. There seems to be a discussion about it here [https://github.com/pschatzmann/ESP32-A2DP/issues/80](https://github.com/pschatzmann/ESP32-A2DP/issues/80) so I am going to give this a try.

**Comment by hhemmati81** [comment]
I ended up using a second esp32 with ground isolation. It works well, and I can turn it on and off through API commands.
