### ISSUE TITLE
Display information

### ISSUE THREAD

**Issue by awholecorndog** [steindevices/ESP32-LyraT-DSP#7]
Hello,
Could you please upload the information to add the OLED display.

**Comment by steindevices** [comment]
I'm currently away and won't be able to get to this until late next week. Will post an update then.

**Comment by steindevices** [comment]
I've added a .pdf that shows how to add the OLED display. You'll find it [here](https://github.com/steindevices/ESP32-LyraT-DSP/blob/main/OLED%20Display/ESP32%20LyraT%20OLED%20Installation.pdf).

Note that I used a typical 0.96"128x64 OLED display when designing my case. If you have something different, you'll need another case design.

**Comment by awholecorndog** [comment]
Thank You
